# -*- coding: utf-8 -*-
"""3_step_debt_searcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVfKYbaj9FMDy9_3MQ_C0Kne2vINOMU2
"""

import gdown
import polars as pl

# id расшаренного файла с результатами оценки
file_id = "1NObLR-GZKolBSAjanF7F_Cq8juHDVh1h"

gdown.download(f"https://drive.google.com/uc?id={file_id}", "rfsd_clear.csv", quiet=False)

rfsd_clear = pl.read_csv("rfsd_clear.csv", dtypes={"inn": pl.String})

rfsd_clear.filter(rfsd_clear['inn'] == "5609196415")

inn_value = input('Введите ИНН проверяемой компании: ')

# Поиск ИНН в DataFrame
filtered_df = (pl.scan_csv("rfsd_clear.csv", schema_overrides={"inn": pl.String})
                .filter(pl.col('inn') == inn_value)
                .collect())

# Проверка, найден ли ИНН
if filtered_df.height == 0:
    print("ИНН не найден, возможно компания не существует или не сдавала бухгалтерскую отчетность")
else:
    # Извлечение значений
    max_debt_value = filtered_df.select('max_debt').item()
    max_debt_shift = filtered_df.select('max_debt_shift').item()
    cred_day_value = filtered_df.select('cred_day').item()
    cred_day_shift = filtered_df.select('cred_day_shift').item()
    prepay_value = filtered_df.select('prepay').item()

    # Проверка значения prepay
    if prepay_value == 'yes':
        print("\n + Авансирование допускается.\nУСЛОВИЯ АВАНСИРОВАНИЯ:")
        # Проверка cred_day
        if cred_day_value == 0:
            print(" - Определить срок выполнения обязательств не удалось. Высокий риск неисполнения!")
            print(f" + Сумма аванса < {max_debt_value:,.0f} ₽ ({max_debt_shift} к прошлому году)".replace(',', ' '))
        elif cred_day_value > 365:
            print(" - Cрок выполнения обязательств слишком большой. Высокий риск неисполнения!")
            print(f" + Сумма аванса < {max_debt_value:,.0f} ₽ ({max_debt_shift} к прошлому году)".replace(',', ' '))
        else:
            print(f" + Сумма аванса < {max_debt_value:,.0f} ₽ ({max_debt_shift} к прошлому году)".replace(',', ' '))
            print(f" + Ориентировочный срок выполнения обязательств не менее {cred_day_value} дней ({cred_day_shift} к прошлому году)")
    else:  # prepay_value == 'no'
        print("Авансирование не допускается.")

rfsd_clear.filter(rfsd_clear['inn'] == inn_value)

